apiVersion: v1
kind: namespace
metadata:
  name: ssl-dns-management
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key
  namespace: ssl-dns-management
type: Opaque
stringData:
  apiKey: <cloudflare-api-key>

# Permissions required for the API key:
# - Zone.Zone:Read
# - Zone.DNS:Edit