provider:
  name: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token-secret
        key: api-token
extraArgs:
  cloudflare-record-comment: provisioned_by_externaldns
