apiVersion: v1
kind: namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: <cloudflare-api-token>

# Permissions required for the API token:
# - Zone.Zone:Read
# - Zone.DNS:Edit